Small steps
strange error with

src/Main.hs:38:1: error:
    Failed to load interface for ‘GHCJS.DOM’
    It is a member of the hidden package ‘jsaddle-dom-0.9.2.0’.
    Perhaps you need to add ‘jsaddle-dom’ to the build-depends in your .cabal file.
    Use -v to see a list of the files searched for.